const projects = [
  {id:'marcom-stories',title:'MarCom Stories',category:'video',label:'Video / Photo',year:'2025',description:'Placeholder for a short- or long-form storytelling project created through Clemson MarCom Student Affairs.',role:'Creative production',type:'Video + photography',client:'Clemson MarCom',bg:'linear-gradient(135deg,#301b56,#a658a6 55%,#f0b1c5)'},
  {id:'local-life',title:'LOCAL Life',category:'editorial',label:'Editorial / Photo',year:'2025',description:'Placeholder for editorial stories, cover work, photography, and page design created for LOCAL Life Magazine.',role:'Multimedia intern',type:'Editorial + design',client:'LOCAL Life Magazine',bg:'linear-gradient(135deg,#d789a7,#45245f 52%,#171020)'},
  {id:'visual-notes',title:'Visual Notes',category:'photo',label:'Photography',year:'2025',description:'Placeholder for an image-led collection of events, businesses, people, places, and everyday visual moments.',role:'Photographer',type:'Photo series',client:'Personal work',bg:'linear-gradient(120deg,#191225,#5941a3 50%,#d3b9ff)'},
  {id:'print-objects',title:'Print Objects',category:'design',label:'Design / Print',year:'2024',description:'Placeholder for print, publication, packaging, and production projects developed through Graphic Communications coursework.',role:'Designer',type:'Print production',client:'Clemson University',bg:'linear-gradient(135deg,#342448,#bf84cf 54%,#ffcfbd)'},
  {id:'social-in-motion',title:'Social in Motion',category:'video',label:'Social / Video',year:'2023',description:'Placeholder for social-first video and visual content made to document programs, people, and community experiences.',role:'Visual storyteller',type:'Social content',client:'Young Leaders Organizing Institute',bg:'linear-gradient(135deg,#161225,#4f3c9b 50%,#dd8fbc)'}
];

function projectCard(project,index){return `<a class="project-card" data-category="${project.category}" href="project.html?id=${project.id}"><div class="project-image" style="--project-bg:${project.bg}"><span class="project-index">0${index+1}</span><span class="project-arrow">↗</span></div><div class="project-meta"><span>${project.title}</span><span>${project.label} · ${project.year}</span></div></a>`}
function renderProjects(filter='all'){const grid=document.querySelector('#project-grid');if(!grid)return;grid.innerHTML=projects.map((p,i)=>projectCard(p,i)).join('');grid.querySelectorAll('.project-card').forEach(card=>{if(filter!=='all'&&card.dataset.category!==filter)card.classList.add('is-hidden')})}
function renderDetail(){const target=document.querySelector('#project-detail-content');if(!target)return;const id=new URLSearchParams(location.search).get('id');const project=projects.find(p=>p.id===id)||projects[0];document.title=`${project.title} — Alyssa Franck`;target.innerHTML=`<div class="detail-header"><div><p class="section-kicker">${project.label} / ${project.year}</p><h1>${project.title.split(' ').slice(0,-1).join(' ')} <em>${project.title.split(' ').slice(-1)}</em></h1></div><p class="detail-intro">${project.description}</p></div><div class="detail-visual" style="--project-bg:${project.bg}"><span class="project-index">Placeholder visual / add project media here</span></div><div class="detail-meta"><div><strong>Role</strong><span>${project.role}</span></div><div><strong>Format</strong><span>${project.type}</span></div><div><strong>Client / context</strong><span>${project.client}</span></div></div><div class="detail-caption"><p>This project page is ready for your final images, video, and a short caption. Add the story behind the work here: what the project was, what you contributed, and what the audience needed to feel or understand.</p><a href="index.html#contact">Interested in working together? ↗</a></div>`}
document.addEventListener('DOMContentLoaded',()=>{renderProjects();renderDetail();document.querySelectorAll('.filter-button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(b=>b.classList.remove('is-active'));button.classList.add('is-active');renderProjects(button.dataset.filter)}))});
